# Generated by scripts/bump-brew-formula.mjs — do not edit by hand.
class GrowtherC5 < Formula
  desc "Growther.ai C5 — self-contained V8-bytecode agent runtime"
  homepage "https://growther.ai"
  version "2026.9.8-v265"

  on_macos do
    if Hardware::CPU.arm?
      url "https://raw.githubusercontent.com/growtherai/release/main/dist/c5/v2026.9.8-v265/growther-node22-macos-arm64.tar.gz"
      sha256 "629d2834c0b1d6270ab67f786e1ef0e2ea0d6667370756b8a91507d50990c069"
    end
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/growtherai/release/main/dist/c5/v2026.9.8-v265/growther-node22-macos-x64.tar.gz"
      sha256 "c6d1e9336eedc9d619f5073ebf44f7bbc8475347fbb5fb309e7a165b25a59926"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/growtherai/release/main/dist/c5/v2026.9.8-v265/growther-node22-linux-x64.tar.gz"
      sha256 "34a6f9f2b1580db75a8c2b8ecff380c4fdc3e0a7c5dc0d5684bf37fccfc40825"
    end
  end

  def install
    # Keep the binary and its signed build_manifest.json together in libexec and
    # symlink the binary into bin: process.execPath resolves the symlink, so the
    # manifest is found via the adjacent (Zero-Install) attestation path.
    binary = Dir["growther-*"].reject { |f| f.end_with?(".json") }.first
    libexec.install binary => "growther"
    libexec.install "build_manifest.json" if File.exist?("build_manifest.json")
    bin.install_symlink libexec/"growther"
  end

  test do
    system "#{bin}/growther", "version"
  end
end
