# Generated by scripts/bump-brew-formula.mjs — do not edit by hand.
class GrowtherC5 < Formula
  desc "Growther.ai C5 — self-contained V8-bytecode agent runtime"
  homepage "https://growther.ai"
  version "2026.9.27-v314"

  on_macos do
    depends_on macos: :ventura
    if Hardware::CPU.arm?
      url "https://raw.githubusercontent.com/growtherai/release/main/dist/c5/v2026.9.27-v314/growther-c5-macos-arm64-node24.tar.gz"
      sha256 "759daac031cc58cf50214182d5d2b1771b99406295e56e4e01fadd530dba91e6"
    end
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/growtherai/release/main/dist/c5/v2026.9.27-v314/growther-c5-macos-x64-node24.tar.gz"
      sha256 "a003fc3f6929d723479ad398cf9632d628f3cd9a8c17091026a709b05c32f3c0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/growtherai/release/main/dist/c5/v2026.9.27-v314/growther-c5-linux-x64-node24.tar.gz"
      sha256 "0b32c9ec7f959ce19e8af6f9dbb5f53e8d2b3ca00bc80022d61b303c07cdc17b"
    end
  end

  def install
    # Keep the binary and its signed build_manifest.json together in libexec and
    # symlink the binary into bin: process.execPath resolves the symlink, so the
    # manifest is found via the adjacent (Zero-Install) attestation path.
    binary = Dir["growther-*"].reject { |f| f.end_with?(".json") }.first
    libexec.install binary => "growther"
    libexec.install "build_manifest.json" if File.exist?("build_manifest.json")
    bin.install_symlink libexec/"growther"
  end

  test do
    system "#{bin}/growther", "version"
  end
end
