# Generated by scripts/bump-brew-formula.mjs — do not edit by hand.
class GrowtherC5 < Formula
  desc "Growther.ai C5 — self-contained V8-bytecode agent runtime"
  homepage "https://growther.ai"
  version "2026.9.4-v243"

  on_macos do
    if Hardware::CPU.arm?
      url "https://raw.githubusercontent.com/growtherai/release/main/dist/c5/v2026.9.4-v243/growther-node22-macos-arm64.tar.gz"
      sha256 "e299fcc78f7c81e400934b3dd4d1ed3b16e24190e4904050e5c5ef7fe56d1975"
    end
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/growtherai/release/main/dist/c5/v2026.9.4-v243/growther-node22-macos-x64.tar.gz"
      sha256 "fc3ca4062b3eb539bb14ec371f8eaf9238e7accf0c6556242b74f660318aa8f0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/growtherai/release/main/dist/c5/v2026.9.4-v243/growther-node22-linux-x64.tar.gz"
      sha256 "0f31a148322e14dd5589a7a5aa20018a1944e39a5602362246026ab5b21d93dc"
    end
  end

  def install
    # Keep the binary and its signed build_manifest.json together in libexec and
    # symlink the binary into bin: process.execPath resolves the symlink, so the
    # manifest is found via the adjacent (Zero-Install) attestation path.
    binary = Dir["growther-*"].reject { |f| f.end_with?(".json") }.first
    libexec.install binary => "growther"
    libexec.install "build_manifest.json" if File.exist?("build_manifest.json")
    bin.install_symlink libexec/"growther"
  end

  test do
    system "#{bin}/growther", "version"
  end
end
